### PR TITLE
Update VCS support for Noetic

### PR DESCRIPTION
**Pull request by bsb808**
Updated instructions for using `vcs` to clone dependent source repos.

I tested this by compiling in a docker container and running this example:
```
roslaunch smilodon_gazebo smilodon.launch 
roslaunch uuv_dave joy_thrusterop.launch namespace:=smilodon
```

I suspect there maybe more regressions that need to be discovered.

Note: the https://github.com/Field-Robotics-Lab/nps_uw_multibeam_sonar.git repo is not included in the list b/c it doesn't work (yet) in docker.

### CODE REVIEW

**Comment by M1chaelM** [comment]
I'm getting the errors below when trying to [follow the tutorial](https://github.com/Field-Robotics-Lab/dave/wiki/Clone-Dave-Repositories):
```
=== ./ds_msgs (git) ===
Could not determine ref type of version: git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./ds_sim (git) ===
Could not determine ref type of version: git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bsb808** [comment]
The urls are for school access, so you need to register ssh keys with bitbucket.  Or infer the https url. I'll put a note in the wiki, but this is expected behavior.

**Comment by M1chaelM** [comment]
Regarding CUDA support: @woensug-choi has this working in his own test image, but I believe it requires building from the Nvidia CUDA base image rather than from a ROS base image. Using this would require us to change how we make all our test images (again). However, there is currently a draft PR for a --cuda option to rocker that should make this problem go away: https://github.com/osrf/rocker/pull/126

**Comment by woensug-choi** [comment]
@M1chaelM I've made a branch [`origin/woensug/v4.0_test`](https://github.com/Field-Robotics-Lab/dave/tree/origin/woensug/v4.0_test) since I had to use Nvidia's cudagl (cuda + opengl) docker hub image to test multibeam sonar plugin.

As you have already guessed, using the base image of Nividia's cudagl works well on 20.04-Noetic-Gazebo11 for multibeam sonar too. If needed, I can make -cuda option for ./build.bash.

The branch includes a single set of Dockerfile/build.bash/run.bash/join.bash that can build both melodic and noetic with and without Nvidia options (default to 20.04-Noetic-Gazebo11 if no options provided). It might be redundant if it's too different from the usage you are planning for VRX and.  Yet, it would be a good material to compare since multiple launch files ran fine with the `Dockerfile` and the `.repos` in the branch.

|                                  | 18.04 Melodic Gazebo9 Nvidia | 18.04 Melodic Gazebo9 Non-Nvidia | 20.04 Noetic Gazebo11 Nvidia | 20.04 Noetic Gazebo11 Non-Nvidia |
|----------------------------------|------------------------------|----------------------------------|------------------------------|----------------------------------|
| Base Image | nvidia/cudagl:11.3.0-devel-ubuntu18.04   | ubuntu:bionic   | nvidia/cudagl:11.3.0-devel       |  ubuntu:focal     |
| Build                            | ./build.bash melodic         | ./build.bash -w melodic          | ./build.bash                 | ./build.bash -w                  |
| Run                              | ./run.bash                   | ./run.bash -w                    | ./run.bash                   | ./run.bash -w                    |
| Join                             | ./join.bash                  | ./join.bash -w                   | ./join.bash                  | ./join.bash -w                   |
| dave_demo .launch (Docker)        | :heavy_check_mark:           | :heavy_check_mark:               | :heavy_check_mark:           | :heavy_check_mark:               |
| dave_demo .launch (Direct)        | :heavy_check_mark:           | :heavy_check_mark:               | :heavy_check_mark:           | :heavy_check_mark:               |
| dave_demo .launch (Docker in WSL) | :heavy_multiplication_x: too slow     | :heavy_check_mark:               | :heavy_multiplication_x:   too slow   | :heavy_check_mark:               |
| dave_demo .launch (Direct in WSL) | :heavy_check_mark:     | :heavy_check_mark:               | :heavy_check_mark:     | :heavy_check_mark:               |
| Multibeam sonar (Docker) | :heavy_check_mark:     | :heavy_multiplication_x:               | :heavy_check_mark:     | :heavy_multiplication_x:               |
| Multibeam sonar (Direct) | :heavy_check_mark:     | :heavy_multiplication_x:               | :heavy_check_mark:     | :heavy_multiplication_x:               |
| Multibeam sonar (Docker in WSL) | :heavy_multiplication_x:     | :heavy_multiplication_x:               | :heavy_multiplication_x:     | :heavy_multiplication_x:               |
| Multibeam sonar (Direct in WSL) | :heavy_check_mark:     | :heavy_multiplication_x:               | :heavy_check_mark:     | :heavy_multiplication_x:               |

**Comment by woensug-choi** [comment]
@bsb808 These two files went without problems for me.
Without multibeam sonar repo : https://github.com/Field-Robotics-Lab/dave/blob/origin/woensug/v4.0_test/extras/repos/dave_sim.repos
With multibeam sonar repo : https://github.com/Field-Robotics-Lab/dave/blob/origin/woensug/v4.0_test/extras/repos/dave_sim_multibeam.repos

Also, I've edited final testing script of the docker installation tutoral to `roslaunch dave_demo_launch dave_demo.launch` since `roslaunch smilodon_gazebo smilodon.launch` and `roslaunch uuv_dave joy_thrusterop.launch namespace:=smilodon` are from the legacy folder.

I can't test them since I don't have a joystick, but if you are to test them try with
```
roslaunch dave_robot_launch smilodon.launch
roslaunch dave_nodes joy_thrusterop.launch namespace:=smilodon
```

**Comment by bsb808** [comment]
I'd like to divide and conquer here.

Step 1: Let's get the VCS list updated for the "base" dave functionality - without multibeam sonar repo.  The reason is that, as far as I can tell, this does not work with our existing (r)docker setup.
Step 2: @M1chaelM and @woensug-choi - Make a new issue and/or PR to address getting the multibeam sonar repo working from the (r)docker container.  Recommend copying the excellent discussion above (on multibeam sonar repo) into the new issue/PR.

This PR is exclusively for Step 1.  Please review and make sure it works for standard cases, without multibeam sonar repo.

Once the PR is approved we'll have a standard, but not complete, dev. environment for wiki and v3.1_reorg testing.

**Comment by M1chaelM** [comment]
The vcstool installation is can be either `python3-vcstool` or `python-vcstool`, depending on your setup. To prevent having to think about it I added it to the Docker supporting docker images in dockwater repo.

**Comment by bsb808** [comment]
> python-vcstool

I'll add a note to the wiki.  I typically have vcstool on the host since I use it for numerous projects.  Is `python-vcstool` exclusively python2?

**Review by M1chaelM — CHANGES_REQUESTED** [review]
This builds fine for me on our Noetic test image from the [dockwater repository](https://github.com/Field-Robotics-Lab/dockwater), but when I run with:
```
roslaunch dave_demo_launch dave_demo.launch
```
The mechanical arm consistently fails with the following error:
```
[rexrov/oberon7/gripper_controller_oberon7-16] process has died [pid 21205, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_control/gripper_controller.py joy:=/rexrov/joy __name:=gripper_controller_oberon7 __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-gripper_controller_oberon7-16.log].
log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-gripper_controller_oberon7-16*.log
[rexrov/oberon7/kinematics_service-17] process has died [pid 21241, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_kinematics/kinematics_service.py __name:=kinematics_service __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-kinematics_service-17.log].
log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-kinematics_service-17*.log
[rexrov/oberon7/joint_position_controller_oberon7-18] process has died [pid 21242, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_control/joint_position_controller.py joy:=/rexrov/joy __name:=joint_position_controller_oberon7 __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-joint_position_controller_oberon7-18.log].
log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-joint_position_controller_oberon7-18*.log
```
@crvogt Do you get a similar error or is it working for you?

**Comment by M1chaelM** [comment]
> > python-vcstool
> 
> I'll add a note to the wiki. I typically have vcstool on the host since I use it for numerous projects. Is `python-vcstool` exclusively python2?

No, there is a python3 version also (looks like you found it).

**Comment by crvogt** [comment]
@M1chaelM This isn't an error I've seen, but trying it out now.

**Comment by bsb808** [comment]
@M1chaelM you can run the node standalone (outside the launch file) or use "output="screen"" in the node tag to be able to see the output.  If the shebang is /usr/env python - then it likely is a python3 issue.

**Comment by M1chaelM** [comment]
@bsb808 @mabelzhang @crvogt I just created branch  fix_static_checks to resolve the CI errors we're seeing in PRs into v3.1_reorganization.

**Comment by crvogt** [comment]
@M1chaelM The example is working for me under the "old" organization structure.

**Comment by bsb808** [comment]
> @M1chaelM The example is working for me under the "old" organization structure. Have yet to try it with v3.1_reorganization.

@crvogt 
* Are you testing in a docker container - or directly on the host?
* Will be good to know if the v3.1_reorganization branch works as well.

**Comment by crvogt** [comment]
@bsb808 Directly on the host. Just about to try it with the v3.1_reorganization branch.

**Comment by M1chaelM** [comment]
@bsb808 I thought I was supposed to test against the v3.1_reorganization branch because it looks like the PR is merging into that branch. Is that right? Apologies if I'm confused.

**Comment by crvogt** [comment]
> @bsb808 I thought I was supposed to test against the v3.1_reorganization branch because it looks like the PR is merging into that branch. Is that right? Apologies if I'm confused.

It makes sense to do this regardless. I thought it'd be helpful to mention it does work for me under the original org on host.

**Comment by crvogt** [comment]
@M1chaelM The example is working for me on my host machine under the v3.1_reorganization branch. Running a minimal workspace (dave, ds_*, uuv_*)

**Comment by bsb808** [comment]
> @bsb808 @mabelzhang @crvogt I just created branch fix_static_checks to resolve the CI errors we're seeing in PRs into v3.1_reorganization.

Could you make a PR from branch fix_static_checks back to v3.1_reorganization so that we can test and merge?

**Comment by bsb808** [comment]
As discussed, modified URLs for ds_* repos to point to the Field Robotics Lab forks of WHOI's bitbucket project: https://github.com/Field-Robotics-Lab/dave/pull/128/commits/af4851b6156a0b293eaa8a08ce45b5d3fcca2068

**Comment by bsb808** [comment]
> This builds fine for me on our Noetic test image from the [dockwater repository](https://github.com/Field-Robotics-Lab/dockwater), but when I run with:
> 
> ```
> roslaunch dave_demo_launch dave_demo.launch
> ```
> 
> The mechanical arm consistently fails with the following error:
> 
> ```
> [rexrov/oberon7/gripper_controller_oberon7-16] process has died [pid 21205, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_control/gripper_controller.py joy:=/rexrov/joy __name:=gripper_controller_oberon7 __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-gripper_controller_oberon7-16.log].
> log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-gripper_controller_oberon7-16*.log
> [rexrov/oberon7/kinematics_service-17] process has died [pid 21241, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_kinematics/kinematics_service.py __name:=kinematics_service __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-kinematics_service-17.log].
> log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-kinematics_service-17*.log
> [rexrov/oberon7/joint_position_controller_oberon7-18] process has died [pid 21242, exit code 1, cmd /home/mrmccarr@ern.nps.edu/uuv_ws/devel/lib/uuv_manipulators_control/joint_position_controller.py joy:=/rexrov/joy __name:=joint_position_controller_oberon7 __log:=/home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-joint_position_controller_oberon7-18.log].
> log file: /home/mrmccarr@ern.nps.edu/.ros/log/3a8bea0c-efd4-11eb-ab8c-0242ac110002/rexrov-oberon7-joint_position_controller_oberon7-18*.log
> ```
> 
> @crvogt Do you get a similar error or is it working for you? I'm wondering whether this is a `python3` compatibility issue for `kinematics_service.py` and `joint_position_controller.py` in the `uuv_manipulators` repo.

Will wait for the issue above to get sorted out - then hoping for an approval - then I'll merge.

**Comment by M1chaelM** [comment]
> > @bsb808 @mabelzhang @crvogt I just created branch fix_static_checks to resolve the CI errors we're seeing in PRs into v3.1_reorganization.
> 
> Could you make a PR from branch fix_static_checks back to v3.1_reorganization so that we can test and merge?

Yes. This is already created. See #129

**Comment by M1chaelM** [comment]
@bsb808 @crvogt The quick and dirty fix of just adding "3" to the end of python in the shebangs did not work.

Can anyone get to this to run using our current noetic docker image? I've updated the tutorial so you should be able to reproduce the environment I'm using: https://github.com/Field-Robotics-Lab/dave/wiki/Installation

I will try the debugging suggests Brian mentioned above to get more error info.

**Comment by M1chaelM** [comment]
After poking around a bit further, it looks like the `uuv_manipulators` repository is not ported to Python3. @crvogt do you think you could take a look at this?

**Comment by woensug-choi** [comment]
> 
> 
> @bsb808 @crvogt The quick and dirty fix of just adding "3" to the end of python in the shebangs did not work.
> 
> Can anyone get to this to run using our current noetic docker image? I've updated the tutorial so you should be able to reproduce the environment I'm using: https://github.com/Field-Robotics-Lab/dave/wiki/Installation
> 
> I will try the debugging suggests Brian mentioned above to get more error info.

I've made a noetic docker image from dockwater uploaded at the Docker hub to run CI tests. Is this related?
https://github.com/Field-Robotics-Lab/dave/blob/167962ccc1df255f95fe6a6149b35dfaa1e26615/.github/workflows/ci.yml#L10

**Comment by bsb808** [comment]
@crvogt - I'm working on this.   I have updated uuv_manipulators to Noetic/python3 - but there are still some unmet dependencies in my docker image....

**Comment by bsb808** [comment]
Good catch @M1chaelM 

Added two PRs for other repos:
* https://github.com/Field-Robotics-Lab/dockwater/pull/3
* https://github.com/Field-Robotics-Lab/uuv_manipulators/pull/3

With those changes, I now have this example running without errors
```
roslaunch dave_demo_launch dave_demo.launch
```

Let's clear those two PRs, then someone verify they get the same results and approve this one.  Thank you guys!

**Comment by bsb808** [comment]
@dtdavi1 The same thing seems to have happened now with this PR.

**Comment by bsb808** [comment]
Closing this PR because the rebasing of the v3.1_reorganization.  See new PR at https://github.com/Field-Robotics-Lab/dave/pull/137

**Pull request closed without merging**
