### PR TITLE
DVL Model and Plugin Update

### PR DESCRIPTION
**Pull request by dtdavi1**
Updated dvl_gazebo package to include URDF (Xacro) models for performer-specific DVLs using the UUV Simulator DVL plugin.  

Added SDF and URDF models and examples implementing the WHOI DSL environment plugins.

The DVL tutorial on the wiki page (https://github.com/Field-Robotics-Lab/dave/wiki/whn_dvl_examples), which corresponds to the package README.md file, has been updated to include instructions and documentation for the new UUV Simulator models and the WHOI DSL environment models.

### CODE REVIEW

**Comment by bsb808** [comment]
Fantastic.  I'm a little backlogged with class and the sonar plugin.  @BruceMty would you have time to review?

**Comment by BruceMty** [comment]
I can look at this tomorrow.

**Comment by bsb808** [comment]
Running the tests...

Both of the WHN examples generate the following warnings...
`roslaunch dvl_gazebo uuvsim_teledyne_whn_standalone.launch`

```
Warning [parser.cc:626] Can not find the XML attribute 'version' in sdf XML tag for model: NED frame. Please specify the SDF protocol supported in the model configuration file. The first sdf tag in the config file will be used 
[INFO] [1589318904.850189, 0.000000]: Calling service /gazebo/spawn_urdf_model
Warning [parser_urdf.cc:1119] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
Warning [parser_urdf.cc:1119] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
Warning [parser_urdf.cc:1119] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
Warning [parser_urdf.cc:1119] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
```

Perhaps this is expected since...
```
NOTE for all models and macros: Gravity has been disabled for all of these models for the time being so that they can be incorporated without additional plugins and controllers.
```

**Comment by BruceMty** [comment]
Wiki questioins, ref. https://github.com/Field-Robotics-Lab/dave/wiki/whn_dvl_examples#uuv-simulator-plugin-utilization:

Launch files are not present.  Were they renamed?

Does "choosing to "follow" the teledyne_whn model" mean to keep the DVL in the Gazebo GUI view by moving the mouse?

Running "roslaunch dvl_gazebo teledyne_whn_standalone.launch":
1) Only 1 of 4 ray sets is blue.  Is this expected?
2) Can we resolve two warnings: a) XML attribue 'version' and b) multiple inconsistent <gravity>?

**Comment by bsb808** [comment]
> Does "choosing to "follow" the teledyne_whn model" mean to keep the DVL in the Gazebo GUI view by moving the mouse?

In Gazebo - you can locate the model on the left, then right-click on it and select "Follow" so the camera follows the model.

**Comment by bsb808** [comment]
I was able to run the WHOI examples without issue.

Great job on the writeup / notes.

It seems we should schedule some time to discuss where to go from here.  I suspect that the WHOI model is the preferred starting point and that we can start adding functionality from there.

**Comment by bsb808** [comment]
I approved - assuming that @dtdavi1 will resolve the warnings comment above.

Recommend working with @BruceMty to sort out the issues he discusses, but appears good to go from my location.

**Comment by dtdavi1** [comment]
The missing "version" warning comes from the NED frame model that is included in the world file.  Both the world file itself and the included NED file are in the UUV Simulator codebase--I can make the warning go away, but the "fix" would be limited to our local fork.

The gravity warnings are a byproduct of the gravity being disabled for the links for now (since the "robot" isn't powered, the whole thing just falls like a rock if gravity is enabled).

**Comment by dtdavi1** [comment]
@BruceMty, I left a separate comment about the warnings (we're stuck with the gravity ones for now, and the version one comes from the UUV Simulator codebase--neither actually means anything functionally).

I'm not sure about the ray color--they should all be blue, but can render differently depending on the viewing angle and light position.

The names did change in the dvl_dev branch (I moved them when I added the WHOI sim stuff) but the changes were already reflected in the wiki tutorial.  I've completed the merge, so if you update from master, then everything should work per the tutorial.

**Pull request merged**
