### PR TITLE
add environment with tank and target

### PR DESCRIPTION
**Pull request by BruceMty**
This introduces a Sonar, target, and tank environment, please see https://github.com/Field-Robotics-Lab/DAVE/wiki/Sonar-Models#run-in-basement-tank-environment for views.

A choice here is to create .sdf files for the tank, target, and Sonar models.  An alternative might be to make separate .xacro files for each to enable configurability of each model.  Going forward, we might want to remove model duplication in fls_gazebo/worlds/blueview_standalone.world.

### CODE REVIEW

**Comment by arascon05** [comment]
1. When I launch rqt_image_view I need to select blueview_p900/image_depth_sonar to get the same view as yours. When I click on the /depth/image_raw_sonar I get a gray screen.

2. roslaunch gtri_based_fls blueview_basement_cylinder.launch - I launched mine using roslaunch gtri_based_sonar_gazebo blueview_basement_cylinder.launch 

I don't have a gtri_based_fls....should I?

**Comment by arascon05** [comment]
3. My rqt_image_view also does not look like yours. It looks like the one from your first picture in the tutorial (blue background yellow sonar returns)

**Comment by BruceMty** [comment]
The behavior you mention is expected for the current master head.  You need to select this branch and rebuild.

Also, this works with the basement_world branch of gtri_based_sonar.  Maybe these two repositories should be merged?

**Comment by bsb808** [comment]
Note - this PR is parallel with GTRI Sonar [PR#1](https://github.com/Field-Robotics-Lab/gtri_based_sonar/pull/1) - so need to evaluate both PR's simultaneusly.

**Comment by BruceMty** [comment]
This merge adds two things: 1) a basement tank and target, along with launch files for fls_gazebo, and 2) laser_retro property for models useful for GTRI-based Sonar.

**Pull request merged**
