### PR TITLE
standalone launch for multi-vehicle stratified current demo

### PR DESCRIPTION
**Pull request by j-herman**

### CODE REVIEW

**Comment by j-herman** [comment]
Just adding in a missing launch file so the multi-vehicle transient current demo will run.  File copied from master branch into dave_demo_launch/launch folder.

**Comment by bsb808** [comment]
@j-herman How do you run this example - i.e., how would you like a reviewer to test the modification prior to approval?

Is there an associated wiki/tutorial?

Finally, it is a good idea to add a preferred reviewer so that folks get tagged and we can coordinate.

Thank you!

**Comment by j-herman** [comment]
> @j-herman How do you run this example - i.e., how would you like a reviewer to test the modification prior to approval?
> 
> Is there an associated wiki/tutorial?
> 
> Finally, it is a good idea to add a preferred reviewer so that folks get tagged and we can coordinate.
> 
> Thank you!

In work!  I wanted to get the checks started asap.  

This file supports the multi-vehicle portion of the Ocean Current tutorial (https://github.com/Field-Robotics-Lab/dave/wiki/Ocean-Current).  To run the demo:
roslaunch dave_demo_launch dave_transientcurrent_demo.launch 
In a second terminal:
roslaunch dave_demo_launch dave_transient_current_multi.launch

To observe the two different current values (Smilodon's should be larger):
rostopic echo /hydrodynamics/current_velocity/smilodon
rostopic echo /hydrodynamics/current_velocity/rexrov

**Comment by bsb808** [comment]
When I try the first (there is a typo in your roslaunch)
```
roslaunch dave_demo_launch dave_transient_current_demo.launch
```

I get errors which look like they are associated with python3.
```
Package pymap3d is not available, WGS84 coordinates cannot be used
Download pymap3d for Python 2.7 as
>> sudo pip install pymap3d==1.5.2
or for Python 3.x as
>> sudo pip install pymap3d
spawn_model script started
Traceback (most recent call last):
  File "/home/bsb/uuv_ws/devel/lib/uuv_manipulators_control/gripper_controller.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_control/scripts/gripper_controller.py", line 18, in <module>
    from uuv_manipulator_interfaces import GripperInterface
  File "/home/bsb/uuv_ws/devel/lib/python3/dist-packages/uuv_manipulator_interfaces/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_kinematics/src/uuv_manipulator_interfaces/gripper.py", line 25
    from __future__ import division
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
Traceback (most recent call last):
  File "/home/bsb/uuv_ws/devel/lib/uuv_manipulators_kinematics/kinematics_service.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_kinematics/scripts/kinematics_service.py", line 22, in <module>
    from uuv_manipulator_interfaces import ArmInterface
  File "/home/bsb/uuv_ws/devel/lib/python3/dist-packages/uuv_manipulator_interfaces/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_kinematics/src/uuv_manipulator_interfaces/gripper.py", line 25
    from __future__ import division
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
Traceback (most recent call last):
  File "/home/bsb/uuv_ws/devel/lib/uuv_manipulators_control/joint_position_controller.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_control/scripts/joint_position_controller.py", line 19, in <module>
    from uuv_manipulator_interfaces import ArmInterface
  File "/home/bsb/uuv_ws/devel/lib/python3/dist-packages/uuv_manipulator_interfaces/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
  File "/home/bsb/uuv_ws/src/uuv_manipulators/uuv_manipulators_kinematics/src/uuv_manipulator_interfaces/gripper.py", line 25
    from __future__ import division
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
[rexrov/oberon7/gripper_controller_oberon7-15] process has died [pid 8184, exit code 1, cmd /home/bsb/uuv_ws/devel/lib/uuv_manipulators_control/gripper_controller.py joy:=/rexrov/joy __name:=gripper_controller_oberon7 __log:=/home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-gripper_controller_oberon7-15.log].
log file: /home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-gripper_controller_oberon7-15*.log
[INFO] [1627671058.271940, 0.000000]: Loading model xml from ros parameter
[INFO] [1627671058.275430, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1627671058.280946, 0.000000]: Using the ENU coordinates to spawn the model
[INFO] [1627671058.282534, 0.000000]: Initial position wrt the world frame: (4.00, 4.00, -93.00)
[INFO] [1627671058.284418, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1627671058.285095, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
[rexrov/oberon7/kinematics_service-16] process has died [pid 8203, exit code 1, cmd /home/bsb/uuv_ws/devel/lib/uuv_manipulators_kinematics/kinematics_service.py __name:=kinematics_service __log:=/home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-kinematics_service-16.log].
log file: /home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-kinematics_service-16*.log
[rexrov/oberon7/joint_position_controller_oberon7-17] process has died [pid 8227, exit code 1, cmd /home/bsb/uuv_ws/devel/lib/uuv_manipulators_control/joint_position_controller.py joy:=/rexrov/joy __name:=joint_position_controller_oberon7 __log:=/home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-joint_position_controller_oberon7-17.log].
log file: /home/bsb/.ros/log/12f0baba-f167-11eb-bb9f-0242ac110003/rexrov-oberon7-joint_position_controller_oberon7-17*.log
Gazebo multi-robot simulator, version 11.7.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [GuiIface.cc:200] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin 
Gazebo multi-robot simulator, version 11.7.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
```

**Comment by bsb808** [comment]
I'm running in the docker image with the VCS repositories.

I think we'll need to address this PR post 4.0.0

**Comment by bsb808** [comment]
After we merge the v3.1_reorganization branch, please change the destination branch of this PR to master.

**Comment by mabelzhang** [comment]
FYI if you delete the `v3.1_reorganization` branch after merging that PR (there will be a delete branch button), this PR will automatically retarget to `master`.

**Comment by j-herman** [comment]
Typo fixed, and I'll make the changes to the PR.  It looks like the problem is somewhere other than this file so I will start running in docker and see if I can track it down.

**Comment by woensug-choi** [comment]
It works as it's supposed to be. I think it would be better if the demo launch can show both vehicles in the gazebo window by changing the vehicle and camera positions. @j-herman As this PR is for a standalone launch file, this PR is good to go even if you don't modify the vehicle and camera position.

I am seeing random crashes with UnderwaterObjectPlugin.cc. Something I have not seen in Melodic environments. This error is not specific to this PR. It happens for our basic `dave_demo.launch` too at both host install and docker environment. I've been working to investigate (will post an issue for this soon).

**Review by woensug-choi — APPROVED** [review]
A standalone launch for the multiple vehicle tutorial works fine

**Comment by j-herman** [comment]
> It works as it's supposed to be. I think it would be better if the demo launch can show both vehicles in the gazebo window by changing the vehicle and camera positions.
> 
That's a good thought.  I will look into making the changes.

**Pull request merged**
