### PR TITLE
adding github action for continuous integration test

### PR DESCRIPTION
**Pull request by M1chaelM**
A github action to test pushed code, based on the one used for the [vrx repository](https://github.com/osrf/vrx/blob/master/.github/workflows/ci.yml).

### CODE REVIEW

**Comment by M1chaelM** [comment]
@caguero would you mind taking a look? I am confused about the code_check.sh script. When you call it, it appears to have no arguments, so I thought it was just a placeholder. However, when I do the same thing in the repo it fails so I must be missing something.

**Comment by M1chaelM** [comment]
Note: since we have not been using code_check.sh, one of our header files was not passing the tests it runs (gazebo_ros_image_sonar.hh). Instead of creating a separate PR for these minor adjustments, I've just included them here, and I'm adding @BruceMty to double check that I didn't mess this up (it still seems to build fine so I think it should be OK).

**Comment by M1chaelM** [comment]
@caguero Sorry for all the chatter. It looks like I broke the testing while trying to figure out how to pull in the other repositories we need to build against. Do you know how to do this properly? If not I will come back and look into it later today.

**Comment by BruceMty** [comment]
> Note: since we have not been using code_check.sh, one of our header files was not passing the tests it runs (gazebo_ros_image_sonar.hh). Instead of creating a separate PR for these minor adjustments, I've just included them here, and I'm adding @BruceMty to double check that I didn't mess this up (it still seems to build fine so I think it should be OK).

This file needs to go away, but we need to resolve issue https://github.com/Field-Robotics-Lab/dave/issues/25 first.  Changes to gazebo_ros_image_sonar.hh are fine if "roslaunch uuv_dave uuv_dave.launch" works.

**Comment by M1chaelM** [comment]
> > Note: since we have not been using code_check.sh, one of our header files was not passing the tests it runs (gazebo_ros_image_sonar.hh). Instead of creating a separate PR for these minor adjustments, I've just included them here, and I'm adding @BruceMty to double check that I didn't mess this up (it still seems to build fine so I think it should be OK).
> 
> This file needs to go away, but we need to resolve issue #25 first. Changes to gazebo_ros_image_sonar.hh are fine if "roslaunch uuv_dave uuv_dave.launch" works.

Understood. Thanks Bruce.

**Comment by M1chaelM** [comment]
@caguero Does this look OK with you? I'm hoping to get these tests in place before we merge the rest of the PRs leading up to release 2.0

**Comment by M1chaelM** [comment]
Sorry @caguero but do you think you could look at this today? Thanks!

**Comment by caguero** [comment]
> @caguero would you mind taking a look?
> 
> EDIT: Please disregard the question below. I found the paths in the script itself and I am no longer confused.
> 
> I am confused about the code_check.sh script. When you call it, it appears to have no arguments, so I thought it was just a placeholder. However, when I do the same thing in the repo it fails so I must be missing something.

That's the c++ static checker. It looks into some directories for C++ code.

**Review by caguero — APPROVED** [review]
Looks good to me and CI is :green_circle:

**Pull request merged**
