### PR TITLE
Three Glider models

### PR DESCRIPTION
**Pull request by woensug-choi**
Made models for three glider types
- glider_hybrid_whoi
  - a body + two propellers (independently rotating)
  - no detailed texture
- glider_slocum
  - a body + a propeller (independently rotating)
  - detailed texture
- glider_wave_liquidrobotics
  - a float + a submerged + a joint + a umbilical, rotating axis specified for joint and umbilical
  - detailed texture for float

Things to do later,
- Inertial properties
- Buoyancy plugin properties
- Glider dynamics plugin properties (UUV simulator use different formats to define models and their properties)
Screenshot
Screenshot
Screenshot

### CODE REVIEW

**Comment by bsb808** [comment]
Could you create a new world file that has all the models included?

Please add a new wiki page under Demonstrations ->Models->Vehicle models to demonstrate the new capability.  Include in the wiki the commands (roslaunch, etc.) to launch the models (they can be static - just to illustrate) and include images so readers know what to expect when they run the command.

**Comment by woensug-choi** [comment]
### **Launch files with robot description in xacro and urdf formats are added for gliders.**
There are three glider namespaces (Slocum, hybrid_whoi, wave_liquidrobotics).

**File hierarchy**
- launch/uuv_glider_$(namespace).launch
  - launch/upload_glider_$(namespace).launch
    - urdf/glider_$(namespace)_default.urdf.xacro
         - urdf/glider_$(namespace).xacro
            - models/$(namespace)/*.dae
            - urdf/glider_$(namespace)_snippets.xacro
            - urdf/glider_$(namespace)_sensors.xacro
```
# to launch
roslaunch uuv_dave uuv_glider_$(namespace).launch
# (e.g.)
roslaunch uuv_dave uuv_glider_slocum.launch
```
### Issues
**1. Sensors can be added at urdf/glider_$(namespace)_sensors.xacro**
**2. Glider kinematics plugins are not yet included (it's under development)**
**3. Joint connection for wave glider should be fixed (what was ok in sdf format is not ok in xacro, urdf format)**

**Comment by woensug-choi** [comment]
While this PR is ready to be reviewed with static launch files to visualize gliders using the commands in the above comments, additional sensor requirements to be added is as follows (Organized and listed by @bsb808).

Asking for specification to WHOI is mentioned at other locations (issues at hybrid glider plugin development repository [issues for glider_hybrid_whoi](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/issues)). Meanwhile, if @BruceMty can help add template sensors at each glider models would be great. sensors are defined at separate sensors.xacro files. It's been commented out.

dave/uuv_dave/urdf/glider_slocum_sensors.xacro
dave/uuv_dave/urdf/glider_hybrid_whoi_sensors.xacro
dave/uuv_dave/urdf/glider_wave_liquidrobotics_sensors.xacro


## Altitude sensor
Need to simulate a glider altitude sensor.

* What currently exists?
    * Couldn't find anything in UUV Simulator - but would be worth looking at.
* If necessary, a simple plugin shouldn't be a big effort.
    * Is there a standard altitude sensor measurement or do we need a new one?

To start with, we can use the model state to infer altitude.  Assume a flat bottom for now and that the seafloor is at the location of the seafloor heightmap model location.  Can assume altitude is measured directly below glider, despite the fact that the altimeter often is based on a slant range to the bottom - we can address that detail in a future pass.

## Depth sensor
Need to simulate a glider depth sensor.

* What currently exists?
    * The UUV Simulator has a pressure sensor plugin.  Is this useful?  Is there documentation?  https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_sensor_plugins/uuv_sensor_ros_plugins/include/uuv_sensor_ros_plugins/SubseaPressureROSPlugin.hh
* If necessary, a simple plugin shouldn't be a big effort.
    * Should it use the WHOI Deep Submergence DepthPressure message?  This doesn't introduce a new dependency and provides some commonality.  https://bitbucket.org/whoidsl/ds_msgs/src/master/ds_sensor_msgs/msg/DepthPressure.msg

Need to simulate the glider's internal dead reckoning localization solution.

* First cut would be to use the Hector Gazebo GPS plugin parameters (particularly drift) to simulate the dead reckoning soluiton.  
    * Do a test to verify that the solution is "reasonable" and consistent with expectations. 

See the [uw_glider_itnerface.graphml](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/master/uw_glider_interface.graphml) for context.

## IMU sensor
Add Hector IMU plugin to hybrid and non-hybrid underwater glider models: http://wiki.ros.org/hector_gazebo_plugins

* Tune the configuration parameters to reflect the glider IMU (attitude and heading sensor performance supplied by WHOI

See the [uw_glider_itnerface.graphml](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/master/uw_glider_interface.graphml) for context.

## GPS sensor
* Add Hector GPS plugin to hybrid and non-hybrid underwater glider models: http://wiki.ros.org/hector_gazebo_plugins
* Tune the GPS configuration parameters to reflect the glider GPS sensor performance supplied by WHOI
* The GPS only gets a fix when at the surface (antenna out of the water).
    * Can we simulate this behavior with the existing plugin?  
    * If not - add an intermediate ROS node in Python that subscribes the the plugin outputs and only published the GPS fix information when glider is at this surface.  Can use the model state information from Gazebo to determine if the glider is at the surface (or some other method).
   * Could also evaluate if the UUV Simulator plugin would be of use https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_sensor_plugins/uuv_sensor_ros_plugins/include/uuv_sensor_ros_plugins/GPSROSPlugin.hh

See the [uw_glider_itnerface.graphml](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/master/uw_glider_interface.graphml)

**Comment by bsb808** [comment]
I was able to run the static examples.  In the future, please put up a wiki with the commands to test and the expected outcome.  Here is a minimal example: for this PR.

https://github.com/Field-Robotics-Lab/dave/wiki/Glider-Models

I have put up some issues that will need to be addressed, but would like to get this PR merged and then work on those issues separately.

* #46 
* #47

**Review by bsb808 — APPROVED** [review]
I was able to run the static examples.  In the future, please put up a wiki with the commands to test and the expected outcome.  Here is a minimal example: for this PR.

https://github.com/Field-Robotics-Lab/dave/wiki/Glider-Models

I have put up some issues that will need to be addressed, but would like to get this PR merged and then work on those issues separately.

* #46 
* #47

**Comment by bsb808** [comment]
I added a small commit with a few tweaks.
https://github.com/Field-Robotics-Lab/dave/pull/31/commits/11cffac3673b97287deb7825622b9638d77dc36d

**Pull request merged**
