### PR TITLE
Integrated World

### PR DESCRIPTION
**Pull request by Yadunund**
An underwater world that showcases various simulator capabilities. See Usage below.

## Pending items:
- [x] Select seabed model. 
  - [x] Currently, this branch has its own copy of the Santorini mode. TODO: Use the model from this PR once it is merged https://github.com/Field-Robotics-Lab/dave/pull/203.
    - Created a new `SantoriniScaled` model that imports the mesh from the original `Santorini` model https://github.com/Field-Robotics-Lab/dave/pull/217/commits/98a6b895f27ad1ee09e5a8a065b9041b262749b0 https://github.com/Field-Robotics-Lab/dave/commit/98a6b895f27ad1ee09e5a8a065b9041b262749b0
  - [x] Consider further scaling the seabed. The current scaling is `0.1`
    - Scaled X & Y to `0.05`. Z remains at `0.1`. https://github.com/Field-Robotics-Lab/dave/pull/219
- [x] Incorporate electrical flying lead https://github.com/Field-Robotics-Lab/dave/pull/223
- [x] Incorporate a mud pit with objects to drag around https://github.com/Field-Robotics-Lab/dave/pull/221
- [x] Incorporate bimanual demo https://github.com/Field-Robotics-Lab/dave/pull/240/
- [x] Script to teleport UUV to various stations/demo sites https://github.com/Field-Robotics-Lab/dave/pull/231
- [x] Add models from https://github.com/Field-Robotics-Lab/dave/pull/242
  - [x] https://app.ignitionrobotics.org/search;q=dave
  - [x] https://github.com/Field-Robotics-Lab/dave/pull/194
  - [x] https://github.com/Field-Robotics-Lab/dave/pull/209
- ~[ ] [Optional] Incorporate multibeam demo https://github.com/Field-Robotics-Lab/dave/pull/222~
- [x] [Optional] Incorporate multiple UUVs with separate joystick control https://github.com/Field-Robotics-Lab/dave/pull/240/

image

## Usage
To launch the demo world
```bash
roslaunch dave_demo_launch dave_integrated_demo.launch
```
## UUVs
The world spawns two UUVs, a single arm `rexrov0` UUV which can be teloperated using a joystick connected to `js0` and a dual arm `rexrov` UUV which can be teleoperted using a joystick connected to `js1`. The arms on this UUV can be commanded via the moveit interface. See Electrical Station below for more information.

## Stations
The world has multiple stations where UUVs can interact with objects and the environment. A helpful script has been developed to quickly "teleport" the desired UUV to the various stations. Run the teleporter script:
```bash
roslaunch dave_nodes integrated_world_teleporter.launch 
```
Then to teleport `rexrov0` to the mudpit, type "rexrov0 mud" (without quotes) and hit enter. The UUV should automatically teleport. Gazebo does not have a service to update the camera view through a service call but this can be done in Ignition which is left for future work. 
Locations include
* artillery
* mud
* home

### Home
The `rexrov0` UUV spwans here
image
The `flight_data_recorder` object can be picked up. The other objects are static to reduce computational load.

## Mud
image
The `rexrov0` can pick up the anchor that is loaded with the mud plugin and drag it along the mud. The vase beside the anchor can also be picked up. The degraded vase and the narrower vase are static to reduce computational load.

## Artillery
image

## Electrical
image
The dual arm `rexrov` spawns here. The arms can be controlled with via `moveit`. First start the controller.
```bash
roslaunch rexrov_oberon7_moveit rexrov_dual_arm_moveit_planning_execution.launch moveit_controller_manager:=rexrov
```
To instruct the UUV to pick up the plug and bring it close to the recepticle
```bash
rosrun dave_nodes bimanual_integrated_world.py 
```
The user can teleoperate the UUV via `js1` to finish the insertion.

### CODE REVIEW

**Comment by j-herman** [comment]
@Yadunund Are you planning to use the bathymetry plugin for tiling with the PR#203 world?  Or will all of the demos be within a single tiled area?

**Comment by Yadunund** [comment]
> @Yadunund Are you planning to use the bathymetry plugin for tiling with the PR#203 world? Or will all of the demos be within a single tiled area?

Hi @j-herman , currently the entire demo is within a single tiled area. Should we switch to relying on the bathymetry plugin instead?

**Comment by j-herman** [comment]
> > @Yadunund Are you planning to use the bathymetry plugin for tiling with the PR#203 world? Or will all of the demos be within a single tiled area?
> 
> Hi @j-herman , currently the entire demo is within a single tiled area. Should we switch to relying on the bathymetry plugin instead?
No preference on my part - just wanted to check in with your plans before I make a mud pit for you :)
Thanks!

**Comment by Yadunund** [comment]
> > > @Yadunund Are you planning to use the bathymetry plugin for tiling with the PR#203 world? Or will all of the demos be within a single tiled area?
> > 
> > 
> > Hi @j-herman , currently the entire demo is within a single tiled area. Should we switch to relying on the bathymetry plugin instead?
> 
> No preference on my part - just wanted to check in with your plans before I make a mud pit for you :) Thanks!

Thanks for letting me know! I've already made a mud pit. Will open a PR later tonight and could really use your feedback 🙂

**Comment by j-herman** [comment]
> > > > @Yadunund Are you planning to use the bathymetry plugin for tiling with the PR#203 world? Or will all of the demos be within a single tiled area?
> > > 
> > > 
> > > Hi @j-herman , currently the entire demo is within a single tiled area. Should we switch to relying on the bathymetry plugin instead?
> > 
> > 
> > No preference on my part - just wanted to check in with your plans before I make a mud pit for you :) Thanks!
> 
> Thanks for letting me know! I've already made a mud pit. Will open a PR later tonight and could really use your feedback slightly_smiling_face

You are way ahead of the game again!  Awesome, can't wait to see it in action.

**Comment by woensug-choi** [comment]
I vote for a singlr tile. Tiling is for long-range search investigation senatios. Integrated world demo is more like a local search :)

**Comment by Yadunund** [comment]
@bsb808 @Yadunund @woensug-choi @crvogt @mabelzhang The integrated world PR is ready to be merged! All the features in the checklist have been incorporated. I've updated the PR description with a `Usage` section to describe all the capabilities. Once merged, I can port the description to a wiki page.

**Comment by quarkytale** [comment]
[https://github.com/Field-Robotics-Lab/dave/wiki/Integrated-World](https://github.com/Field-Robotics-Lab/dave/wiki/Integrated-World)

**Review by j-herman — APPROVED** [review]
I checked out all of the functionality and it is working, although the first time I tried in docker there were some issues with the controllers not loading (ros-noetic-ros-control not installed via rosdep and couldn't be found).  Restarted and everything seemed ok.
Approving without CI check, so we may want to figure out that problem and run the checks here before merging (@bsb808 ?)

**Comment by mabelzhang** [comment]
To be cautious, we should fix the CI related to #239 and #250 before merging this. This is a big branch to merge in. If we need to revert this, it's potentially a lot of work.

**Comment by mabelzhang** [comment]
CI is green!

**Pull request merged**
