### PR TITLE
Update URDF xacros

### LINKED ISSUE #200: xacro error when launching demo worlds
When i run `roslaunch dave_demo_launch dave_demo.launch`, I encounter the error below. 

```
xacro: in-order processing became default in ROS Melodic. You can drop the option.
name 'namespace' is not defined 
when evaluating expression 'namespace'
when processing file: /home/yadu/ws_dave/src/dave/urdf/dave_snippets/urdf/sonar_snippets.xacro
included from: /home/yadu/ws_dave/src/dave/urdf/dave_snippets/urdf/sensor_snippets.xacro
included from: /home/yadu/ws_dave/src/dave/urdf/robots/rexrov_description/urdf/rexrov_base.xacro
included from: /home/yadu/ws_dave/src/dave/urdf/robots/rexrov_description/urdf/rexrov_oberon7.xacro
RLException: while processing /home/yadu/ws_dave/src/dave/urdf/robots/rexrov_description/launch/upload_rexrov_oberon7.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/yadu/ws_dave/src/dave/urdf/robots/rexrov_description/urdf/rexrov_oberon7.xacro', '--inorder', 'debug:=0', 'namespace:=rexrov', 'inertial_reference_frame:=world']] returned with code [2]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro '$(find rexrov_description)/urdf/rexrov_oberon7.xacro' --inorder           debug:=$(arg debug)           namespace:=$(arg namespace)           inertial_reference_frame:=world"/>
The traceback for the exception was written to the log file
```

I'm seeing this only after updating my `noetic` binaries which leads me to believe that the latest release of  `xacro`, `v1.14.11`, has introduced some incompatibility with the xacro files in `dave_snippets`. I suspect it might be related to the namespace changes made as summarised [here](https://github.com/ros/xacro/blob/noetic-devel/CHANGELOG.rst#11411-2022-01-20).

Working on a fix now.

### PR DESCRIPTION
**Pull request by Yadunund**
Fix #200 

To reproduce the problem on `master`: 
1. Upgrade to the latest `xacro` package using the command `sudo apt install --only-upgrade ros-noetic-xacro`. You can then run `dpkg -l | grep ros-noetic-xacro` to view the version of the `xacro` binary. It should be greater than `1.14.10`. 
2. Source `noetic` and build the workspace using `catkin build` or `catkin_make`
3. Source the workspace and run `roslaunch dave_demo_launch dave_demo.launch`. This should lead to the error described in the linked ticket.

To test the fix:
1. Checkout to this branch
2. Build the workspace
3. Source the workspace and launch the demo. The simulation should launch successfully.

### CODE REVIEW

**Comment by j-herman** [comment]
@Yadunund With `ros-noetic-xacro   1.14.13-1focal.20220212.160007`, I am getting different errors than what you're reporting:

> xacro: in-order processing became default in ROS Melodic. You can drop the option.
redefining global symbol: range
when instantiating macro: pressure_plugin_macro (/home/jessica/uuv_ws/src/uuv_simulator/uuv_sensor_plugins/uuv_sensor_ros_plugins/urdf/pressure_snippets.xacro)
instantiated from: default_pressure_macro (/home/jessica/uuv_ws/src/uuv_simulator/uuv_sensor_plugins/uuv_sensor_ros_plugins/urdf/pressure_snippets.xacro)
instantiated from: rexrov_base (/home/jessica/uuv_ws/src/dave/urdf/robots/rexrov_description/urdf/rexrov_base.xacro)
in file: /home/jessica/uuv_ws/src/dave/urdf/robots/rexrov_description/urdf/rexrov_sensors.xacro
included from: /home/jessica/uuv_ws/src/dave/urdf/robots/rexrov_description/urdf/rexrov_oberon7.xacro

The robot_description loads and runs fine.  I do remember seeing the namespace errors at some point while I was troubleshooting another issue yesterday but it seems to be resolved on my system.  It looks like the namespace issues were addressed (see [changelog](http://docs.ros.org/en/noetic/changelogs/xacro/changelog.html) in 1.14.13 - can you give it a shot with the new version and see if we still need the fix?

**Comment by Yadunund** [comment]
@j-herman you're right, `v1.14.13` fixes the regression bug and looks like it was synced just 22hrs ago! https://discourse.ros.org/t/preparing-for-noetic-sync-2022-02-14/24313

No wonder when I updated the package earlier yesterday, it was on `v1.14.11` 😅 

I'll close this PR.

**Comment by j-herman** [comment]
That must have broken a lot of code to get fixed so quickly!

**Comment by mabelzhang** [comment]
Dang, thanks for all the work @Yadunund!!

**Pull request closed without merging**
