### PR TITLE
Elec lead

### PR DESCRIPTION
**Pull request by dtdavi1**
Updated flying lead functionality can be tested with either of the following demos (only the second includes the new plug/receptacle model):
```
ros_launch dave_demo_launch dave_electrical_mate.launch
```
or
```
roslaunch dave_demo_launch dave_plug_and_socket_demo.launch
```

Updates include the following:
Force calculations for insert & extract aligned with the plug link
New meshes and models
     Male-to-female and female-to-male plug/receptacle combos
     Underwater platform model (incorporated into both SDF and URDF demos)
Added ROS functionality to expose calculated force applied to the plug link during insert & extract
    ```rqt_plot /m_to_f_plug/appliedForce/vector``` to visualize the message
Tutorial updates to account for changes

### CODE REVIEW

**Comment by bsb808** [comment]
Is the example `roslaunch dave_demo_launch dave_plug_and_socket_demo.launch` represented in the wiki pages somewhere?    I see `roslaunch dave_demo_launch dave_electrical_mate.launch` in https://github.com/Field-Robotics-Lab/dave/wiki/Electrical-Plug-Mating-Plugin.   

Maybe we could add the first roslaunch to the existing wiki, add a screenshot and explain the differences between the two examples?

**Comment by bsb808** [comment]
I was able to run both roslaunch examples and see that the `/m_to_f_plug/appliedForce/vector` was advertised.  I'm probably not skilled enough to drive the vehicle and arm to test this, so my proposed plan is...

1. Once the documentation (see comment above) is addressed, then I'll approve.
2. Go ahead and merge
3. Find someone to take on https://github.com/Field-Robotics-Lab/dave/issues/193
4. Once we have solved https://github.com/Field-Robotics-Lab/dave/issues/193, use that to test/demonstrate the mating forces and create a highlight video.

@dtdavi1 Sound like a plan?

**Comment by dtdavi1** [comment]
I've updated the wiki some to better differentiate between the two demos (the dave_plug_and_socket_demo is towards the end).  I'm working on a video demo and will finalize that before the release.

**Comment by dtdavi1** [comment]
For a quick test of the plugin functionality, the [world file](https://github.com/Field-Robotics-Lab/dave/blob/elec_lead/models/dave_worlds/worlds/dave_electrical_mating.world) that is used in the dave_electrical_mate.launch demo can be modified as follows:
Comment out line 174
Uncomment line 175

This will position the plug in the socket's opening (but not engaged) upon startup.  The prismatic joint will be formed right after startup, but there won't be enough applied force to lock it.  If you maneuver the RexROV to the stand and lightly bump the plug downward, the joint should lock almost immediately (and should be indicated in the terminal window).

Unlocking will still require you to grab the plug handle with the gripper and pulling upwards (but that's much easier than doing the whole insertion evolution).

**Comment by bsb808** [comment]
@dtdavi1 Both of the launch examples run for me.

I ran the example you suggest to start with the plug aligned.  When I nudge it with the ROV I get some errors reported to the terminal:

```
Msg] m_to_f_socket and m_to_f_plug are aligned in orientation and distance
[Msg] m_to_f_socket and m_to_f_plug within proximity
[Msg] m_to_f_socket-m_to_f_plug joint formed
[Msg] m_to_f_socket-m_to_f_plug joint locked!
Error [Param.cc:457] Out of range. Unable to set value [6.94416e-310 ] for key[upper].
Error [Param.cc:457] Out of range. Unable to set value [6.94416e-310 ] for key[lower].
[Msg] m_to_f_socket-m_to_f_plug joint unlocked!
[Msg] m_to_f_socket-m_to_f_plug joint removed
[Msg] m_to_f_socket and m_to_f_plug are aligned in orientation and distance
```

Are these expected?

**Comment by dtdavi1** [comment]
@bsb808 They're all either expected or at least not surprising.  Here's a summary of what the stream is telling you:
The first is a report that the plug and socket are properly aligned.
The second is a report that the prismatic joint was created (i.e., they've been properly aligned for the requisite amount of time)
The third is a report that the joint was locked (i.e., it's plugged in) because the right amount of pressure was applied
I have no idea what the errors are (they occur on occasion but don't really affect anything).  You can write it up as an issue (or I will) if you want, but I don't think they should prevent the merge.
The "joint unlocked" and "joint removed" mean that it was unplugged.  If you didn't actually grab it and pull, it was probably a byproduct of the plug being jostled when it was plugged in (i.e., it plugged in successfully but then popped loose).
The last line is from the process starting all over because it's not plugged in but is properly aligned.

**Comment by bsb808** [comment]
@dtdavi1 Understood.  The [Msg]s are really helpful and I understood those - it was the Error that makes me unsure if things are operating as expected.

I opened an issue so we can run this to ground post 4.3.0 - https://github.com/Field-Robotics-Lab/dave/issues/227

Please merge when you can.

**Review by bsb808 — APPROVED** [review]
Ready to merge

**Comment by dtdavi1** [comment]
@bsb808 Sounds good.  My best guess is that the error is associated with a race condition that occurs when the joint is locked and then removed too quickly (which occurs somtimes when the insertion is rough).

**Pull request merged**
