### PR TITLE
Add rosinstall

### PR DESCRIPTION
**Pull request by BruceMty**
Using a rosinstall makes it much easier to download all the git repos needed to build the workspace using the wstool package. I added these instructions to the wiki to use with this rosinstall:
### Workspace creation with wstool

Create the DAVE workspace from the included rosinstall

    sudo apt install python-wstool
    mkdir -p ~/uuv_sim/src
    mv dave_sim.rosinstall ~/uuv_sim/src/.
    cd ~/uuv_sim/src
    wstool init
    wstool merge dave_sim.rosinstall
    wstool up

### CODE REVIEW

**Comment by xydesa** [comment]
FYI I have some updates to this that I can push to github, unfortunately I cannot push directly to this branch. I'd have to push to the forked version in my personal space. Let me know what you'd like me to do.

**Comment by bsb808** [comment]
@M1chaelM My recollection is that you were going to take a look at if this is still pertinent.  If not, please re-assign.

**Comment by M1chaelM** [comment]
> FYI I have some updates to this that I can push to github, unfortunately I cannot push directly to this branch. I'd have to push to the forked version in my personal space. Let me know what you'd like me to do.

@xydesa Did you push the updates to your personal space? If they are not too extensive I can port them over manually.

**Comment by M1chaelM** [comment]
> @M1chaelM My recollection is that you were going to take a look at if this is still pertinent. If not, please re-assign.
@bsb808 This is a feature request to add support for [wstool](http://wiki.ros.org/wstool) which provides a layer of abstraction over git or other version control tools. The practical advantage is that it's a little easier to download multiple repositories and keep them up to date.

In my view, we have 4 options:
1. Officially switch over to using `wstool` instead of `git`
2. Accept this pull request for the `rosinstall` file that `wstool` uses, but just provide this as an option to users who prefer to use it.
3. Add a note in the wiki mentioning that `wstool` is available and include Alex's tutorial for using it, but decline this PR.
4. Decline this PR and do nothing.

My recommendation is option 3. I'm opposed to 1 because I don't think the convenience of `wstool` warrants adding a dependency, rewriting our tutorials and modifying the Docker image. And I think if we aren't committing to using wstool instead of git command directly, adding the rosinstall file to our repository means we now have to remember to update it whenever we add repositories. This isn't too bad but presumably the people who we are updating it for are people who are familiar with wstool and could easily produce the file themselves (since it's just a list of repositories).

If you agree I think we can close this PR.

**Comment by bsb808** [comment]
@M1chaelM I believe this is analogous to our discussion about "officially" supported and "community" supported features/dev. environments/etc.

In this case, we are not officially supporting 'wstool' and/or 'vcstool', but want to allow for community support.  As maintainers, the question of the PR review is, "does this PR cause an regressions with the officially supported features?"   It looks like it would do no harm to include the extra file, i.e., we could include the file for community supported tools, but still only officially support basic 'git' usage.  

If this PR does no harm to our officially supported setup, then I'd recommend 2 - the file is included, but it is community supported.  If merging the PR would break something, we just note that and leave it to the community to address what is broken - not the maintainers responsibility.

I'll forward you the git document we have been discussion on official vs. community supported elements.

**Comment by M1chaelM** [comment]
@bbingham-nps OK, no problem. This definitely does not break the release, so if I'm understanding the document you sent I can approve as a project maintainer. I'm not sure I understood the protocol after that--do we need another reviewer to come along from the community and check the intended functionality?

**Comment by xydesa** [comment]
I understand not wanting to officially support something, but there are a few nice benefits from maintaining a rosinstall (for wstool) or repos (for vcs) file:
* `vcs` is recommended on the official ROS wiki: https://wiki.ros.org/melodic/Installation/Source
* It makes managing workspaces for a project with multiple repositories much easier
* It's easy to maintain rosinstall/repos files for past versions of the project (In fact I have rosinstalls for each released version of DAVE that I'd like to add to this PR, but I cannot since I can't push directly to this branch. I'd be happy to open a new PR from a new branch if you'd like those as well).

Seeing as the ROS source installation tutorials recommend using `vcs` now, I'd recommend using `vcs` over `wstool` and switching from the rosinstall file format to the repos file format natively supported by `vcs`. I'd be happy to create a new branch and PR for this work if you're interested. Then you could decline this PR.

**Comment by bsb808** [comment]
Thank you @xydesa.  It is currently on our long list of things we'd like to incorporate into the project.  At this point we have very few resources for this project thanks to funding lags, so we are stretching to keep up with what is already on our plates.

We would love to get a PR and tutorials for using vcs.  I think the community would appreciate the contribution and it shouldn't conflict with out current support/maintanence.

**Comment by xydesa** [comment]
@bsb808 in that case, feel free to decline this PR, and I'll work on a PR for vcs integration and repos files.

**Comment by M1chaelM** [comment]
@xydesa @bsb808 Declined, per discussion. We'll look for the new one with vcs.

**Pull request closed without merging**
