### PR TITLE
New stratified currrent plugin with multiple vehicle support

### PR DESCRIPTION
**Pull request by woensug-choi**
# Stratified Ocean current plugin with multiple vehicle support

At branch [multiple_vehicle_support](https://github.com/Field-Robotics-Lab/dave/tree/multiple_vehicle_support)

## Quick run command
```
roslaunch uuv_dave uuv_dave_transientcurrent_demo.launch
```

## Code structure
image

- dave_world_plugins
  - The plugin is loaded when dave_world_ros_plugins is loaded
  - To read `<constant_current>` parameters and publish global ocean current Gazebo topic
  - To read stratified ocean current database CSV file and save it to the world
- dave_world_ros_plugins
  - The plugin is loaded at `uuv_dave_ocean_waves_transientcurrent.world`
  - To relay global ocean current to ROS topic
  - To relay stratified ocean current database to ROS topic with custom msg format defined at dave_world_ros_plugins_msgs/msg/StratifiedCurrentVelocity.msg
- dave_model_plugins
  - The plugin is loaded at uuv_dave/urdf/rexrov_oberon7_transient_current.xacro
  - To read stratified ocean current database ROS topic and calculate ocean current relative to vehicle depth
  - To publish vehicle-wise ocean current Gazebo topic
  - To publish vehicle-wise ocean current ROS topic

The hydrodynamics plugin (we are using the uuv_simulator plugin which is loaded at uuv_dave/urdf/rexrov_oberon7_transient_current.xacro) uses Gazebo topic to apply hydrodynamics calculations for each vehicle. Not sure if we can have dave_model_plugins publish only ROS topic and make it work for the hydrodynamics plugin (Duane advised me not to have a plugin to publish both ROS and Gazebo topics before).

## Multiple vehicle support how-to
A vehicle being affected by the ocean current is defined at hydrodynamics plugins with `<flow_velocity_topic>` parameter which is at uuv_dave/urdf/rexrov_oberon7_transient_current.xacro. Having it to a vehicle-specific topic, here it is hydrodynamics/current_velocity/rexrov, a vehicle will be affected by it.
```XML
<plugin name="uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
  <flow_velocity_topic>hydrodynamics/current_velocity/$(arg namespace)</flow_velocity_topic>
</plugin>
```
The vehicle-specific topic is published using the dave_model_plugins (dave_transient_current_plugin) which is also at uuv_dave/urdf/rexrov_oberon7_transient_current.xacro
```XML
<plugin name="dave_transient_current_plugin" filename="libdave_transient_current_plugin.so">
  <flow_velocity_topic>hydrodynamics/current_velocity/$(arg namespace)</flow_velocity_topic>
  <base_link_name>$(arg namespace)/base_link</base_link_name>
  <transient_current>
    <topic_stratified_database>stratified_current_velocity_database</topic_stratified_database>
    <velocity_north>
      <noiseAmp>0.3</noiseAmp>
      <noiseFreq>0.0</noiseFreq>
    </velocity_north>
    <velocity_east>
      <noiseAmp>0.3</noiseAmp>
      <noiseFreq>0.0</noiseFreq>
    </velocity_east>
    <velocity_down>
      <noiseAmp>0.3</noiseAmp>
      <noiseFreq>0.0</noiseFreq>
    </velocity_down>
  </transient_current>
</plugin>
```
Here, the `<flow_velocity_topic>` should match with the topic that the hydrodynamics plugin is subscribing to. Also, `<topic_stratified_database>` should match with the ROS database topic at dave_world_ros_plugins which is defined in the world file.

## Multiple vehicle example
- Two vehicles (Rexrov and Smilodon) effective by ocean currents at each vehicle's depths.
- @j-herman provided the launch files after reviewing the plugin features

To demonstrate the functionality of the stratified current capability with multiple vehicles, launch the transient current demo:
```
roslaunch uuv_dave uuv_dave_transientcurrent_demo.launch
```
Once the simulation launches successfully, add the second vehicle:
```
roslaunch uuv_dave smilodon_standalone.launch
```
You can observe the depth-dependent variation on the ROS current topics via:
```
rostopic echo /hydrodynamics/current_velocity/smilodon
rostopic echo /hydrodynamics/current_velocity/rexrov
```
Smilodon is under faster ocean currents than Rexrov according to the database provided. (slower ocean current near seabed)

image

### CODE REVIEW

**Comment by woensug-choi** [comment]
Will remove the draft tag when multiple vehicle example files (launch files) are included.

**Comment by woensug-choi** [comment]
@j-herman Can you review this? I think you have already checked the functionality of this PR when generating the smilodon launch files. The unstable boot-up issues can be posted as a new issue.

By the way, for the figures we post on GitHub, you can upload them by pasting them to the content window at a new issue page and it will upload it somewhere in the GitHub and provide you a hyperlink text that you can use. This way, you don't have to actually upload the figure to the repo.

**Review by j-herman — APPROVED** [review]
Looks good - code works as advertised (adapts stratified current capability to support multiple vehicles).
Verified by running the demo with Rexrov and Smilodon.
One thought on design decisions in this implementation: the code works by adding a plugin to each supported vehicle in the xacro.  This keeps most of the changes localized in the code, which should be helpful for maintaining backwards compatibility.  In the future, if there is a desire to have the transient current applied to a large number of objects rather than to specific vehicles, we may want to take a look at other approaches for efficiency.

**Comment by woensug-choi** [comment]
@j-herman Thank you for the quick review!! I will make a note at the issue board to have the idea for better structure as a to-do list. For now, as the EPIC team wants their glider simulator to run as soon as possible, I will have this merged and make it functional for them.

**Pull request merged**
