### PR TITLE
Bathymetry for next release playground : Candiate 1. Axial Seamount 

### PR DESCRIPTION
**Pull request by woensug-choi**
## Axial Seamount 

image
image

### Launch command

```bash
roslaunch dave_demo_launch dave_Axial_Seamount_demo.launch
```

### New files in this PR
- world file : `dave_Axial_Seamount.world`
- launch file : `dave_Axial_Seamount_demo.launch`
- Model : `dave/models/dave_object_models/models/AxialSeamountPatch`

### Statistics
- Origin of the source data : https://www.marine-geo.org/tools/datasets/30219
    Clague, D.; Caress, D. and J. Paduan, (2022). Preliminary 1-meter resolution
    bathymetric model (ESRI ASCII grids) for the summit region of Axial
    Seamount, version as of 10 March 2021. IEDA. doi:10.26022/IEDA/330219
- Resolution : 75 cm
- Latitude : 46.035 ~ 46.05
- Longitude : -129.93 ~ -129.914
- Size of the patch : (Lat, Lon) = (0.015, 0.016) = Approx 1000 x 1000 meters)
- Maximum Height : -2139.0134277
- Minimum height : -3.4E+38 (garbage data inside)
- Number of vertices of original data = 3072 x 2560

### Conversion method
- `mkbaty.py` automation script at https://github.com/Field-Robotics-Lab/Bathymetry_Converter
- Flags parameters used inside the script : 
   - `ONE_TILE_AT_ORIGIN` : True
   - `SIMPLIFICATION_LEVEL` : 3 ( if set 0; without any simplification, the mesh OBJ would be 350MB~)
      - Size of the OBJ file is 25 MB
- Parameters used:
    - `PREFIX` = AxialSeamountPatch
    - Ranges
       - `STARTLON` = -129.930
       - `STARTLAT` = 46.035
       - `ENDLON` = -129.914
       - `ENDLAT` = 46.050
    - Color texture (`color.txt`)

       ```
       -2190 213 62 79
       -2210 244 109 67
       -2230 254 224 139
       -2245 255 255 191
       -2260 230 245 152
       -2275 171 221 164
       -2290 102 194 165
       -2295 50 136 189
       -2300 94 79 162
       -2315 77 77 77
       -2330 26 26 26
       ``` 

       
@j-herman Are you going to make a wiki? a page for the conversion tutorial? (as I remember from your reply to Brian's mail). I had to introduce bunch of mesh simplification methods in the `mkbathy.py` script. You may give it a look :)

### CODE REVIEW

**Comment by woensug-choi** [comment]
### Tiled version
- On `axial_seamount_tiles` branch at https://github.com/woensug-choi/dave/tree/axial_seamount_tiles
- Size of each tile : (Lat, Lon) = (0.005, 0.005) = Approx 350 x 350meters)
- Tiles to keep on the scene  = 3 tiles

**Comment by j-herman** [comment]
@woensug-choi I was just going to write up a page for using a different/ higher resolution file instead of the sandy bottom heightmap in dave_demo.launch.  Since we don't use the tiling and plugin with the current sandy bottom model that conversion is pretty straightforward.  
This new example looks great!  I'll run it and see how it goes.

**Review by j-herman — APPROVED** [review]
The world looks great!

**Comment by woensug-choi** [comment]
@j-herman Thank you for testing it out! Could you test the other candidate https://github.com/Field-Robotics-Lab/dave/pull/203 too? 

I wonder how we are going to distribute high-resolution bathymetry data. I've put some effort to reduce it to around 20MB for this and another candidate. Github allows a maximum 40 MB file unless we adopt `lf` (https://docs.github.com/en/repositories/working-with-files/managing-large-files) 

For more higher-level discussion, as @bsb808 mentioned in the mail, I understood as this playground wrap-up would not be included in the next release nor the end of march timeline. But worth introducing to them how things will be integrated into this playground (with doneness metric). Meanwhile, your new page preparation will be included in the next release or end of march timeline since it is a definitive demonstration for proof of collaborative possibility with Makai. Am I correct?

**Comment by Yadunund** [comment]
>I wonder how we are going to distribute high-resolution bathymetry data.

One thing we could do is create a script that 1) downloads the dataset 2) runs the Batymetry_Converter on the dataset and 3) installs the output to a share directory at **build time**. Once we have such a script, we would just need to modify the `CMakeLists.txt` file for the `worlds` package such that its executes during `catkin build`. This has worked well for other projects where worlds needed to be auto-generated and where large 3D models needed to be made available to downstream users. Happy to discuss this further if required.

**Comment by j-herman** [comment]
> 
> For more higher-level discussion, as @bsb808 mentioned in the mail, I understood as this playground wrap-up would not be included in the next release nor the end of march timeline. But worth introducing to them how things will be integrated into this playground (with doneness metric). Meanwhile, your new page preparation will be included in the next release or end of march timeline since it is a definitive demonstration for proof of collaborative possibility with Makai. Am I correct?

I thought we were trying to get everything put together by the end of March, including the integrated demo, but maybe I misunderstood.  It's a lot to get done by then!  
I've put together a demo and drafted a wiki on creating a custom seafloor that works more or less like what we already sent to the sponsor via other means, so we will have a record here.  Not sure whether we'll want to incorporate that example but there's a PR in case anyone wants to play around with a new world.

**Comment by woensug-choi** [comment]
Merging it now. Will make a wiki page for both Axial Seamount and Santorini today.

**Comment by woensug-choi** [comment]
Documented at https://github.com/Field-Robotics-Lab/dave/wiki/Bathymetry-Models

**Pull request merged**
