### PR TITLE
Use world solver in ocean waves world

### PR DESCRIPTION
**Pull request by scpeters**
This reduces noise in the force-torque sensor readings and joint velocity measurements to address https://github.com/Field-Robotics-Lab/dave/issues/167.

## Default quick-step solver

This has noise in the force-torque sensor outputs but even more significantly in the joint velocity measurements.

https://user-images.githubusercontent.com/3650755/157762658-1e81f758-8c2e-4b20-b8b5-69189d799e53.mp4

## World-step solver

This significantly reduces noise in all joints, with only the `oberon/pitch` joint showing noise in its velocity measurement.

https://user-images.githubusercontent.com/3650755/157762692-203983c0-d0d1-4681-b203-9560d222c845.mp4

cc @crvogt

### CODE REVIEW

**Comment by mabelzhang** [comment]
Note: Might need to add to other demos as well

**Comment by Yadunund** [comment]
@scpeters I just tried this out with the integrated world and I'm seeing the terminal flooded with these messages 

```
ODE Message 3: LCP internal error, s <= 0 (s=-7.8712e+02)

ODE Message 3: LCP internal error, s <= 0 (s=-8.9315e+09)
```

**Comment by scpeters** [comment]
> @scpeters I just tried this out with the integrated world and I'm seeing the terminal flooded with these messages
> 
> ```
> ODE Message 3: LCP internal error, s <= 0 (s=-7.8712e+02)
> 
> ODE Message 3: LCP internal error, s <= 0 (s=-8.9315e+09)
> ```

sorry I forgot to mention that. This message is annoying but expected with this solver. There is an API call to disable these messages (from [bitbucket pull request 2512](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2512/page/1) merged in https://github.com/osrf/gazebo/commit/dacd9151a198562061ce013d0a70776f821a6ea7). There is currently a way to disable the console messages via the C++ API (`world->GetPhysicsEngine()->SetParam("ode_quiet", true);`), but I'll see if I can make it work from an SDFormat parameter as well.

**Comment by scpeters** [comment]
> > @scpeters I just tried this out with the integrated world and I'm seeing the terminal flooded with these messages
> > ```
> > ODE Message 3: LCP internal error, s <= 0 (s=-7.8712e+02)
> > 
> > ODE Message 3: LCP internal error, s <= 0 (s=-8.9315e+09)
> > ```
> 
> sorry I forgot to mention that. This message is annoying but expected with this solver. There is an API call to disable these messages (from [bitbucket pull request 2512](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2512/page/1) merged in [osrf/gazebo@dacd915](https://github.com/osrf/gazebo/commit/dacd9151a198562061ce013d0a70776f821a6ea7)). There is currently a way to disable the console messages via the C++ API (`world->GetPhysicsEngine()->SetParam("ode_quiet", true);`), but I'll see if I can make it work from an SDFormat parameter as well.

I think we can set it from an SDFormat parameter: see https://github.com/osrf/gazebo/pull/3194

**Review by Yadunund — APPROVED** [review]
Thanks for the clarification. 
Do we want to add the `<ode_quiet>1</ode_quiet>` element here? I'll approve this PR in case nonetheless.

**Comment by scpeters** [comment]
> Thanks for the clarification.
> Do we want to add the `<ode_quiet>1</ode_quiet>` element here? I'll approve this PR in case nonetheless.

added in https://github.com/Field-Robotics-Lab/dave/pull/236/commits/7a23e5009fec0fcc5c3b80843c7de946529f4f1c

**Comment by Yadunund** [comment]
Created a ticket for updating all other worlds in the future. https://github.com/Field-Robotics-Lab/dave/issues/245

**Pull request merged**
