### PR TITLE
Noetic python3

### PR DESCRIPTION
**Pull request by lauralindzey**
This is just another PR fixing the installation of a python script so it'll work with noetic/python3.

I tested this using:
~~~
roslaunch uuv_dave joy_thrusterop.launch namespace:=caracara
~~~

### CODE REVIEW

**Comment by lauralindzey** [comment]
CI fails because frl_msgs doesn't even compile.

(It looks like y'all removed SonarImage.msg in favor of using APL's acoustic_msgs, but didn't fully update your message package)

**Comment by M1chaelM** [comment]
@woensug-choi are you currently working on this PR?

**Comment by woensug-choi** [comment]
> 
> 
> @woensug-choi are you currently working on this PR?

I have not looked in to this. Noetic support is first handled by Carson. But last comments could be a hint to the other PR's github ci problem. Not sure though.

**Review by crvogt — APPROVED** [review]
Workspace compiles fine under Melodic. 
Tested with:
`roslaunch uuv_dave joy_thrusterop.launch` and
`roslaunch uuv_dave uuv_predator.launch`

**Pull request merged**
