### PR TITLE
Updating run.bash to be consistent with VRX workflow

### PR DESCRIPTION
**Pull request by bsb808**
Did small update the the associated docker wiki instructions and `run.bash` to be consistent with the same process for VRX.

Please test these instructions: https://github.com/Field-Robotics-Lab/dave/wiki/noetic_docker

### CODE REVIEW

**Comment by mabelzhang** [comment]
While testing this, I noticed that `build.bash` also needs to be updated.

Currently, `build.bash` names the image `dave_nvidia` by default, checks a `--without-nvidia` arg, and renames to `dave` if necessary.
That applied to the Melodic Dockerfile, which is based on an NVIDIA Docker image.

For Noetic, we're not building on top of an NVIDIA image, we're injecting NVIDIA via Rocker.
So the Docker image name `dave_nvidia` and `--without-nvidia` option are now misleading for Noetic.

Regarding naming, it could just be called `$1`, which will be either `dave_melodic` or `dave_noetic`.
As for `build.bash`, I don't know if we want to update the Melodic image to also use Rocker so that the two images are consistent, or just have 2 different `build.bash` scripts, one for Melodic, one for Noetic.

**Review by M1chaelM — CHANGES_REQUESTED** [review]
@mabelzhang and @bsb808 We now have several repositories that use the same test image, so I've moved the test images to their own repository: https://github.com/Field-Robotics-Lab/dockwater

This is following @bsb808 's suggestion from PR #110, and documented in issue #111. In the interest of keeping our installation environments in sync, I suggest we stop using the Docker-related code in this repository, including the build and run scripts, and switch over to the new common repository. This will require updated Docker install tutorials.

Once the Docker images are consistent, we should update our host-based install tutorials to produce comparable build environments. I've written this up in issue #116.

**Comment by bsb808** [comment]
This is on hold pending @M1chaelM docker unification project.

**Comment by M1chaelM** [comment]
> This is on hold pending @M1chaelM docker unification project.

I think we can now close this.

**Comment by bsb808** [comment]
Closing PR b/c the new [dockwater](https://github.com/Field-Robotics-Lab/dockwater) project takes care of all of this!

**Pull request closed without merging**
