### PR TITLE
Adding repos file for v3.0.0 release.

### PR DESCRIPTION
**Pull request by xydesa**
Signed-off-by: Alexander Xydes <alexander.xydes@navy.mil>

### CODE REVIEW

**Comment by xydesa** [comment]
CI is failing because the docker image it's running in doesn't have Cuda installed, and nps_uw_sensors_gazebo requires cuda to compile now.

**Comment by woensug-choi** [comment]
Thank you for the PR! When are these repo files are used? Added a commit to include [acoustic_msgs](https://github.com/apl-ocean-engineering/acoustic_msgs) repo which is required for new sonar plugin. Please check :)

I've also fixed CI workflow using new docker hub image including cuda installations.

**Comment by xydesa** [comment]
@woensug-choi Thanks for the commit adding the new repository, I've pushed a commit fixing the location where it gets checked out too.

These repos files are a community supported alternative way to create a DAVE workspace with a minimum of commands.
See: https://github.com/Field-Robotics-Lab/dave/wiki/Clone-Dave-Repositories#note-vcstool
and: https://github.com/Field-Robotics-Lab/dave/wiki/vcstool

**Comment by woensug-choi** [comment]
I am merging it here. There will be a PR preparing for v3.1.0 soon (main purpose of the update is to separate multibeam sonar plugin to a different repository so that people would not have to deal with cuda installations if they are not using it). It will be great if you can suggest PRs just like these after. Thank you!

**Pull request merged**
