### PR TITLE
Integrated World - multibeam sonar

### PR DESCRIPTION
**Pull request by woensug-choi**
With, https://github.com/Field-Robotics-Lab/nps_uw_multibeam_sonar/pull/38.
A multibeam sonar can be attached to a robot using URDF

This is on top of https://github.com/Field-Robotics-Lab/dave/pull/217.

I guess this will end up as a separate launch file since it requires NVIDIA gpu and cuda library even though dockwater with -c flag can run it.

```bash
roslaunch dave_demo_launch dave_integrated_demo_multibeam_sonar.launch
```

image

### CODE REVIEW

**Comment by quarkytale** [comment]
We could have two vehicles, one going around different demos and one having the sonar attached to it? It'll great to integrate everything in one launch file/world!

**Comment by woensug-choi** [comment]
@quarkytale Since this PR would require an NVIDIA graphics card, I would suggest it stay at a separate launch file.

**Comment by woensug-choi** [comment]
Will rebase to the latest Integrated world PR next Monday (KST) check everything fits in.

**Comment by woensug-choi** [comment]
Dropping this. Conflict of having an integrated feature demo launch that requires a separate installation process to run multibeam sonar plugin.

**Pull request closed without merging**
