### PR TITLE
GitHub page (On this repo at github_page branch, not fork)

### PR DESCRIPTION
**Pull request by woensug-choi**
This will port out GitHub embedded wiki page into a proper website using the GitHub pages feature.
Related discussion months ago: https://trello.com/c/6errT29A/270-moving-wiki-docs

Currently, this webpage is orientated to use the `github_page` branch

[https://field-robotics-lab.github.io/dave/](https://field-robotics-lab.github.io/dave/)

The main advantages of doing this are
- We can include document updates in PR to review with
- Search optimization for search engines (google), right now our project is almost unsearchable
- Google Analytics for visitor statistics (visit counts, regions, etc)

How it's working
- Markdown documents inside `/docs/contents/` are being rendered

To do 
- [x] Discuss whether we will migrate or not. If so, when?
- [x] Discuss how we are going to host images (as an asset or a link)
- [x] Fix images and document paths
- [x] Add google analytics and apply search optimization
- [x] Apply search optimization

### CODE REVIEW

**Comment by j-herman** [comment]
@woensug-choi Sorry, I missed your request on #232... 
This looks like a really good start - how difficult is it to keep the github.io content synced to the wiki?  Or would this eventually replace the wiki as a better way to do documentation?

**Comment by woensug-choi** [comment]
@j-herman No problem! I found a better way to do this! (this PR, hosting not from the fork but from the branch inside DAVE)
The first thing I need to clear out is that it's not automatically syncing with wiki pages. I've manually copy-pasted some of the markdown text, added a header for github.io, and saved it inside `dave/doc/contents`. We all have to manually go through markdown documents within this PR (the `github_page` branch). When new things are added or modified in the branch, it will automatically recompile the webpage and deploy (takes about 5-10 minutes). This github.io will eventually replace the wiki page. I will ask teams to work on their documents at this week's meeting!

**Comment by woensug-choi** [comment]
Note, for google analytics,
Report link: https://analytics.google.com/analytics/web/#/p306166582/reports/reportinghub?params=_u..nav%3Dmaui
I need to enlist the team's google accounts with privileges to see the reports.

**Comment by mabelzhang** [comment]
This is great. I'd be excited to see this happen. The auto-deployment is great.
The sooner this happens, the less we'll have to sync with our wiki pages' updates :)

Re hosting images
The images that are already in the Wiki, I don't see why we shouldn't host them in the repo too. We're pretty much already hosting them in the wiki repo.
As an example, in Ignition, we host all the tutorial images in a directory https://github.com/ignitionrobotics/ign-gazebo/tree/ign-gazebo6/tutorials/files
With the documentation in the repo, the directory structure will be more visible, and easier to stay organized.

The images that are currently in users' individual uploads, and the wiki is linking to them, i.e. `https://githubusercontent.com`, that is more unclear what we should do.

**Comment by woensug-choi** [comment]
I am planning to ask people to work on this at April :D After all features, video, and screen captures are done.

**Comment by woensug-choi** [comment]
Check out https://field-robotics-lab.github.io/dave.doc

**Comment by woensug-choi** [comment]
It's done!

Now the new GitHub page for dave documentation is hosted at https://field-robotics-lab.github.io/dave.doc

The main advantages of doing this are
- We can include document updates in PR to review with
- Search optimization for search engines (google), right now our project is almost unsearchable
- Google Analytics for visitor statistics (visit counts, regions, etc)

How it's working
- Markdown documents inside `/docs/contents/` are being rendered

Tasks done
- [x] Migrate dave wiki pages to dave.doc
- [x] Fix images and document paths
- [x] Add google analytics and apply search optimization
- [x] Add comment feature that automatically writes an Issue post with `Dave.Doc💬` label (e.g. https://github.com/Field-Robotics-Lab/dave/issues/255) 
- [ ] Mark dave wiki as depreciated or remove the entire dave wiki and link `wiki` link on README to `dave.doc`

**Pull request closed without merging**
