### PR TITLE
Update repo name and location for acoustic messages

### PR DESCRIPTION
**Pull request by rolker**
This addresses #268.

### CODE REVIEW

**Comment by lauralindzey** [comment]
In order to future-proof this, you may want to use a specific tag or commit for the marine_msgs repo, rather than having it use `main`.

**Comment by mabelzhang** [comment]
Might fix errors like this one on `acoustic_msgs` https://github.com/Field-Robotics-Lab/dave/issues/272
But the package names in hydrographic_msgs have also been changed, right? So `acoustic_msgs` are no longer that, it has to be changed to [`marine_acoustic_msgs`](https://github.com/apl-ocean-engineering/marine_msgs/tree/main/marine_acoustic_msgs) now?

😅 I got confused in that issue, because now there's another package that's been released and called `acoustic_msgs` 😅 and that one had a genuine error that we ran into a few weeks back. It could get very confusing for somebody.

It `marine_msgs` still for Noetic? I ask because that's what DAVE targets. If you will have different branches, it would also help if we can use the Noetic one here.

I don't have a setup to test it anymore. I don't know if anybody has at this point. So I don't know if we'll be merging PRs.

**Comment by lauralindzey** [comment]
@mabelzhang -- just a note that I'm at sea, and will be getting home late August. I tried (and failed) to get marine_acoustic_msgs properly released before I left, so it's close to the top of my stack for when I get home.

> But the package names in hydrographic_msgs have also been changed, right? So acoustic_msgs are no longer that, it has to be changed to [marine_acoustic_msgs](https://github.com/apl-ocean-engineering/marine_msgs/tree/main/marine_acoustic_msgs) now?

Correct.

**Review by woensug-choi — CHANGES_REQUESTED** [review]
Thank you for the PR! 
Could you change the `version:main` to `tags/v2.0.0`? This way we can fix it to the v2.0.0 tag for future-proof

**Comment by mabelzhang** [comment]
Ooh that's a good idea.

**Pull request merged**
