### PR TITLE
Fixing static check errors

### PR DESCRIPTION
**Pull request by M1chaelM**
Creating a draft so I can see the output of cppcheck on our current CI image.

### CODE REVIEW

**Comment by M1chaelM** [comment]
I'm seeing an old problem where the static checker wants us to use a header guard style that calculated based on the wrong path:
```
./gazebo/dave_gazebo_world_plugins/include/ocean_current_world_plugin.h:19:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_WORLD_PLUGINS_INCLUDE_OCEAN_CURRENT_WORLD_PLUGIN_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_world_plugins/include/gauss_markov_process.h:19:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_WORLD_PLUGINS_INCLUDE_GAUSS_MARKOV_PROCESS_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_world_plugins/include/tidal_oscillation.h:19:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_WORLD_PLUGINS_INCLUDE_TIDAL_OSCILLATION_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_model_plugins/include/ocean_current_model_plugin.h:19:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_MODEL_PLUGINS_INCLUDE_OCEAN_CURRENT_MODEL_PLUGIN_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_ros_plugins/include/pulse_lidar_plugin.h:17:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_ROS_PLUGINS_INCLUDE_PULSE_LIDAR_PLUGIN_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_ros_plugins/include/ocean_current_plugin.h:20:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_ROS_PLUGINS_INCLUDE_OCEAN_CURRENT_PLUGIN_H_  [build/header_guard] [5]
./gazebo/dave_gazebo_ros_plugins/include/spherical_coordinates_interface.h:18:  #ifndef header guard has wrong style, please use: ___W_DAVE_DAVE_GAZEBO_DAVE_GAZEBO_ROS_PLUGINS_INCLUDE_SPHERICAL_COORDINATES_INTERFACE_H_  [build/header_guard] [5]
```
This does not occur when the checker is run locally. It only shows up when the image is run in CI. I think we've encountered this before but not yet sure what the fix is.

**Comment by M1chaelM** [comment]
@caguero This is the latest version of issue #59. Any ideas?

**Comment by M1chaelM** [comment]
This seems to have spontaneously switched to claiming that the branch has conflicts in the following files:
```
gazebo/dave_gazebo_model_plugins/include/ocean_current_model_plugin.h
gazebo/dave_gazebo_model_plugins/src/ocean_current_model_plugin.cc
gazebo/dave_gazebo_ros_plugins/include/ocean_current_plugin.h
gazebo/dave_gazebo_ros_plugins/include/pulse_lidar_plugin.h
gazebo/dave_gazebo_ros_plugins/include/spherical_coordinates_interface.h
gazebo/dave_gazebo_ros_plugins/src/ocean_current_plugin.cpp
gazebo/dave_gazebo_ros_plugins/src/pulse_lidar_plugin.cpp
gazebo/dave_gazebo_world_plugins/include/gauss_markov_process.h
gazebo/dave_gazebo_world_plugins/include/ocean_current_world_plugin.h
gazebo/dave_gazebo_world_plugins/include/tidal_oscillation.h
gazebo/dave_gazebo_world_plugins/src/ocean_current_world_plugin.cc
```
I'm confused because I don't see any conflicts locally...

**Comment by M1chaelM** [comment]
OK, here's what happened:
* We merged #120 into branch v3.1_reorganization
* This changed the location of many files that this PR is trying to fix.
* It also changes what the recommended header guard is supposed to me, making me doubt the wisdom of using this header guard check for this project.
* For some reason, github (not right away but eventually) detects this impending conflict and refuses to run the CI tests until it is fixed, which temporarily defeats the purpose of this draft PR.

What I am going to do:
1. Resolve the merge conflicts
2. Disable the header guard checks.
3. Request review.

**Comment by M1chaelM** [comment]
Now static checks are passing, but, as feared, this reveals that our build checks are not passing.

**Comment by M1chaelM** [comment]
@woensug-choi Thank you for looking at this! I hope we can get it merged relatively soon before other changes affect the CI.

**Comment by woensug-choi** [comment]
@M1chaelM The build in Ubuntu CI uses gazebo9-melodic-nvidiaCuda image hosted on my Docker Hub account. https://github.com/Field-Robotics-Lab/dave/actions/runs/1077860715/workflow. I will build a clean image using dockwater and change, upload at the docker hub, and change the workflow. Or, do you have a image on the docker hub?

**Comment by woensug-choi** [comment]
@M1chaelM Phew.... and Hurray! I got the green check mark!

**Comment by woensug-choi** [comment]
@M1chaelM Summary of what's been done.
- cpplint fixes
- shadow variable amendements (multiple use of iterable variable `ii`)
- add depdency `${${PROJECT_NAME}_EXPORTED_TARGETS}` to include msg/srv
- removed `hydrographic_msgs` repo (only required for multibeam sonar)
- Changed CI check image to Focal-Noetic-Gazebo11

**Review by woensug-choi — APPROVED** [review]
CI fail (static check and compile using docker image) is fixed. Modifications are made for just those purposes. No feature related changes are made. And of course, it compiles at local machine without any error. Self-approving.

**Comment by mabelzhang** [comment]
Nice work guys! I'm not quite awake yet, but just wanted to note for future reference re header guards if you ever want to enable it again. Maybe changing the configuration to just do the file name itself, not the full path, is a better option. That's how we name our header guards in ROS and Gazebo.

**Pull request merged**
