### PR TITLE
Dave.doc github page is ready!

### PR DESCRIPTION
**Pull request by woensug-choi**
It's done!

Now the new GitHub page for dave documentation is hosted at https://field-robotics-lab.github.io/dave.doc

The main advantages of doing this are
- We can include document updates in PR to review with
- Search optimization for search engines (google), right now our project is almost unsearchable
- Google Analytics for visitor statistics (visit counts, regions, etc)

How it's working
- Markdown documents inside `/docs/contents/` are being rendered

Tasks done
- [x] Migrate dave wiki pages to dave.doc
- [x] Fix images and document paths for menu navigation bar
- [x] Add the last modified date at every post head and foot
- [x] Add light/dark mode switch button
- [x] Add google analytics and apply search optimization
       - [Google analytics report](https://analytics.google.com/analytics/web/#/p306166582/reports/reportinghub?params=_u..nav%3Dmaui%26_u..pageSize%3D25)
- [x] Add a comment system that automatically writes an Issue post with `Dave.Doc💬` label
        - e.g. https://github.com/Field-Robotics-Lab/dave/issues/255
- [x] Mark the dave wiki as depreciated or remove the entire dave wiki and link `wiki` link on README to `dave.doc` (this PR)

### CODE REVIEW

**Comment by quarkytale** [comment]
I just remembered I haven't added the dedicated integrated world video to the wiki. Is that supposed to go on the website as well?

**Comment by mabelzhang** [comment]
I think Brian has the final say on this PR.

I guess a main point is, what's the merge policy in the new repo? Is it basically, org members can merge without approvals (to have the convenience we had with the wiki), and external contributors need approvals (so that not just anyone can merge without approvals)?

@quarkytale New content could be added by opening PRs against the new repo https://github.com/Field-Robotics-Lab/dave.doc/tree/master/contents , if we're happy with going forward with that repo.

Re deprecation (last item on the checklist), you were probably already planning on it, but we should probably put some very large text at the top of the wiki redirecting people to the new documentation site.

**Comment by woensug-choi** [comment]
@mabelzhang  I am proposing something like this
- Org members can push to `main` without approvals
- External users need to make PR at `dave.doc` to change documents
- Every new feature or change of functionality PR on `dave` should include a PR on `dave.doc`

Yes, a very large text to redirect ppl to the `dave.doc` would do :D

**Comment by woensug-choi** [comment]
By doing the SEO(Search engine optimization, pretty much automatic since I have linked with google analytics), googling `Project dave` finds the new webpage as third on the search results :D. Adding `description` at the page header will improve searchability

**Pull request merged**
